ServerEvents.recipes(event =>{
    /**
    {
     type:,
     filter:{},
     original:,
     replace:
    }
    */
    const replace_recipes = [
        {
            type:'input',
            filter:{mod:'functionalstorage'},
            original:'#balm:wooden_chests',
            replace:'sophisticatedstorage:upgrade_base'
        },
        {
            type:'input',
            filter:{output:'cobblefordays:tier_2'},
            original:'minecraft:glass',
            replace:'cobblefordays:tier_1'
        },
        {
            type:'input',
            filter:{output:'cobblefordays:tier_3'},
            original:'#forge:ingots/iron',
            replace:'create:andesite_alloy'
        },
        {
            type:'input',
            filter:{output:'cobblefordays:tier_3'},
            original:'minecraft:glass',
            replace:'apotheosis:mythic_material'
        },
        {
            type:'input',
            filter:{output:'ae2:quartz_glass'},
            original:'#forge:glass',
            replace:'create_crystal_clear:andesite_glass_casing'
        },
        {
            type:'input',
            filter:{output:'create:mechanical_mixer'},
            original:'create:whisk',
            replace:'kubejs:gold_whisk'
        },
        {
            type:'input',
            filter:{output:'create:mechanical_mixer'},
            original:'create:cogwheel',
            replace:'create:large_cogwheel'
        },
        {
            type:'input',
            filter:{output:'ae2:quartz_growth_accelerator'},
            original:'#forge:ingots/iron',
            replace:'apotheosis:mythic_material'
        },
        {
            type:'input',
            filter:{output:'create:display_board'},
            original:'create:electron_tube',
            replace:'create:belt_connector'
        },
        {
            type:'input',
            filter:{output:'ae2:quartz_growth_accelerator'},
            original:'ae2:fluix_block',
            replace:'ae2:flawless_budding_quartz'
        },
        {
            type:'input',
            filter:{output:'minecraft:dispenser'},
            original:'#forge:dusts/redstone',
            replace:'apotheosis:epic_material'
        },
        {
            type:'input',
            filter:{output:'minecraft:redstone_torch'},
            original:'#forge:dusts/redstone',
            replace:'apotheosis:epic_material'
        },
        {
            type:'input',
            filter:{output:'minecraft:comparator'},
            original:'#forge:gems/quartz',
            replace:'#forge:gems/quartz'
        },
        {
            type:'input',
            filter:{output:'minecraft:cauldron'},
            original:'#forge:ingots/iron',
            replace:'psi:psimetal'
        },
        {
            type:'input',
            filter:{output:'minecraft:hopper'},
            original:'#forge:ingots/iron',
            replace:'psi:psimetal'
        },
        {
            type:'input',
            filter:{output:'minecraft:sticky_piston'},
            original:'#forge:slimeballs',
            replace:'apotheosis:uncommon_material'
        },
        {
            type:'input',
            filter:{input:'minecraft:obsidian'},
            original:'minecraft:obsidian',
            replace:'kubejs:obsidian'
        },
        {
            type:'input',
            filter:{output:'modularrouters:blast_upgrade'},
            original:'minecraft:iron_bars',
            replace:'kubejs:sky_nugget'
        },
        {
            type:'input',
            filter:{output:'modularrouters:fluid_upgrade'},
            original:'#forge:glass',
            replace:'botania:bifrost_perm'
        },
        {
            type:'input',
            filter:{output:'modularrouters:sync_upgrade'},
            original:'#forge:dusts/redstone',
            replace:'apotheosis:epic_material'
        },
        {
            type:'input',
            filter:{output:'minecraft:clock'},
            original:'#forge:dusts/redstone',
            replace:'apotheosis:epic_material'
        },
        {
            type:'input',
            filter:{output:'modularrouters:pickup_delay_augment'},
            original:'#forge:slimeballs',
            replace:'apotheosis:uncommon_material'
        },
        {
            type:'input',
            filter:{output:'modularrouters:redstone_augment'},
            original:'#forge:dusts/redstone',
            replace:'apotheosis:epic_material'
        },
        {
            type:'input',
            filter:{output:'minecraft:comparator'},
            original:'#forge:gems/quartz',
            replace:'ae2:fluix_crystal'
        },
        {
            type:'input',
            filter:{output:'modularrouters:regulator_augment'},
            original:'#forge:gems/quartz',
            replace:'ae2:fluix_crystal'
        },
        {
            type:'input',
            filter:{output:'botania:glimmering_livingwood'},
            original:'#forge:dusts/glowstone',
            replace:'apotheosis:rare_material'
        },
        {
            type:'input',
            filter:{output:'botania:glimmering_livingwood_log'},
            original:'#forge:dusts/glowstone',
            replace:'apotheosis:rare_material'
        },
        {
            type:'input',
            filter:{output:'botania:mana_pylon'},
            original:'botania:mana_diamond',
            replace:'kubejs:mana_certus_quartz_crystal'
        },
        {
            type:'input',
            filter:{output:'botanypots:terracotta_botany_pot'},
            original:'minecraft:flower_pot',
            replace:'kubejs:gem_water'
        },
        {
            type:'input',
            filter:{output:'botanypots:terracotta_hopper_botany_pot'},
            original:'minecraft:flower_pot',
            replace:'kubejs:gem_water'
        },
        {
            type:'input',
            filter:{output:'ae2:not_so_mysterious_cube'},
            original:'ae2:controller',
            replace:'ars_nouveau:blue_archwood_wood'
        },
        {
            type:'input',
            filter:{output:'ae2:not_so_mysterious_cube'},
            original:'ae2:smooth_sky_stone_block',
            replace:'botania:gaia_ingot'
        },
        {
            type:'input',
            filter:{output:'create:pulse_extender'},
            original:'create:brass_sheet',
            replace:'create:iron_sheet'
        },
        {
            type:'input',
            filter:{output:'create:pulse_repeater'},
            original:'create:brass_sheet',
            replace:'create:iron_sheet'
        }]

    replace_recipes.forEach(replace_recipe =>{
        if(replace_recipe.type == 'input'){
            event.replaceInput(replace_recipe.filter,replace_recipe.original,replace_recipe.replace)
        }else{
            event.replaceOutput(replace_recipe.filter,replace_recipe.original,replace_recipe.replace)
        }
    })
})