ServerEvents.recipes(event =>{
    const id_prefix = 'compact_world:recipes/other_recipes/smithing/'
    /**
    {
     output:,
     base_input:,
     addition_input:,
     id:`${id_prefix}`
    }
    */
    const recipes = [
        {
            output:'functionalstorage:gold_upgrade',
            base_input:'kubejs:functionalstorage_upgrade_base',
            addition_input:'minecraft:gold_block',
            id:`${id_prefix}functionalstorage_gold_upgrade`
        },
        {
            output:'sophisticatedstorage:stack_upgrade_tier_3',
            base_input:'sophisticatedstorage:upgrade_base',
            addition_input:'minecraft:gold_block',
            id:`${id_prefix}sophisticatedstorage_stack_upgrade_tier_3`
        },
        {
            output:'sophisticatedstorage:basic_to_gold_tier_upgrade',
            base_input:'sophisticatedstorage:upgrade_base',
            addition_input:'minecraft:gold_block',
            id:`${id_prefix}sophisticatedstorage_basic_to_gold_tier_upgrade`
        },
        {
            output:'sophisticatedbackpacks:stack_upgrade_tier_2',
            base_input:'sophisticatedbackpacks:upgrade_base',
            addition_input:'minecraft:gold_block',
            id:`${id_prefix}sophisticatedbackpacks_stack_upgrade_tier_2`
        },
        {
            output:'create:mechanical_saw',
            base_input:'create:andesite_casing',
            addition_input:'elementalcraft:drenched_saw_blade',
            id:`${id_prefix}mechanical_saw`
        },
        {
            output:'sophisticatedstorage:basic_to_diamond_tier_upgrade',
            base_input:'sophisticatedstorage:basic_to_gold_tier_upgrade',
            addition_input:'minecraft:diamond',
            id:`${id_prefix}basic_to_diamond_tier_upgrade`
        },
        {
            output:'sophisticatedstorage:gold_to_diamond_tier_upgrade',
            base_input:'minecraft:gold_ingot',
            addition_input:'minecraft:diamond',
            id:`${id_prefix}gold_to_diamond_tier_upgrade`
        },
        {
            output:'functionalstorage:diamond_upgrade',
            base_input:'functionalstorage:gold_upgrade',
            addition_input:'minecraft:diamond',
            id:`${id_prefix}diamond_upgrade`
        },
        {
            output:'ae2things:disk_housing',
            base_input:'ae2:item_cell_housing',
            addition_input:'sophisticatedstorage:basic_to_diamond_tier_upgrade',
            id:`${id_prefix}disk_housing`
        },
        {
            output:'expatternprovider:wireless_connect',
            base_input:'entangled:block',
            addition_input:'ae2:fluix_glass_cable',
            id:`${id_prefix}wireless_connect`
        },
        {
            output:'expatternprovider:wireless_tool',
            base_input:'entangled:item',
            addition_input:'ae2:fluix_glass_cable',
            id:`${id_prefix}wireless_tool`
        }]

    recipes.forEach(recipe =>{
        event.recipes.minecraft.smithing(recipe.output,recipe.base_input,recipe.addition_input).id(recipe.id)
    })
})