    /**
    {
     id:[],
     information:[]
    }
    */

const tooltips_rei_information = [
    {
        id:['kubejs:compact_dust'],
        information:['\u00a7ashift+神奇的木棍\u00a7c右键\u00a7f紧实型压缩空间壁\u00a7c获得']
    },
    {
        id:['kubejs:compact_ingot'],
        information:['\u00a7a拿着\u00a7f压缩粉末\u00a7c右键\u00a7f压缩空间壁\u00a7c获得']
    },
    {
        id:['psi:cad_assembly_iron'],
        information:['\u00a7a拿着\u00a7f压缩CAD机体\u00a7c右键\u00a7f紧实型压缩空间壁\u00a7c获得']
    },
    {
        id:['kubejs:water_droplet'],
        information:['\u00a7ashift+空手\u00a7c右键\u00a7f草方块\u00a7a有2%概率\u00a7c获得']
    },
    {
        id:['minecraft:water'],
        information:['\u00a7a拿着\u00a7f水滴\u00a7c右键\u00a7f泥土\u00a7c获取']
    },
    {
        id:['psi:psimetal'],
        information:['\u00a7a关于用什么方式产生\u00a7c爆炸\u00a7f请前往任务查看\u00a7a(有较为详细的教程)']
    },
    {
        id:['kubejs:psiknife'],
        information:['用\u00a7c魔源宝石\u00a7f在工作台内合成的方式\u00a7a可以修复耐久\u00a7c(不会被彻底破坏)']
    },
    {
        id:['naturesaura:gold_leaf'],
        information:['\u00a7a无法使用\u00a7c原版方式\u00a7a获得，\u00a7f请使用魔改方式获取']
    },
    {
        id:['hexerei:belladonna_flower'],
        information:['打\u00a7a草/高草\u00a7f有\u00a7c20%概率\u00a7f掉落']
    },
    {
        id:['kubejs:source_psicoal'],
        information:["\u00a7a可以燃烧\u00a7c4个\u00a7a物品"]
    },
    {
        id:['elementalcraft:firecrystal'],
        information:["\u00a7a可以燃烧\u00a7c32个\u00a7a物品"]
    },
    {
        id:['minecraft:flint'],
        information:["\u00a7c不可以通过打破\u00a7a沙砾\u00a7f的方式获得，\u00a7a请使用\u00a7c农夫乐事的砧板\u00a7f获得"]
    },
    {
        id:['naturesaura:offering_table'],
        information:["\u00a7c只能在主世界合成，在微缩世界合成不会有掉落物！\n\u00a7a合成成功以后掉落物会因为上方有紧实型压缩空间墙壁而掉不进来\n\u00a7d你需要制作物品收集器将其收集进来"]
    },
    {
        id:[/createcasing:.*_depot/],
        information:["\u00a7c拿着对应的机壳右键置物台"]
    },
    {
        id:[/createcasing:.*_mixer/],
        information:["\u00a7c拿着对应的机壳右键动力搅拌器"]
    },
    {
        id:[/createcasing:.*_press/],
        information:["\u00a7c拿着对应的机壳右键置物台动力辊压机"]
    },
    {
        id:['ae2:flawless_budding_quartz'],
        information:["\u00a7c可以被挖掘且掉落原方块(不需要精准采集)"]
    },
    {
        id:['mythicbotany:gjallar_horn_full'],
        information:["\u00a7c具体合成方式见任务内"]
    },
    {
        id:['mythicbotany:petrunia_floating'],
        information:["\u00a7a如果附近有足够魔力,\u00a7c(浮空)符文矮牵牛花可以自动激活仪式"]
    },
    {
        id:['kubejs:obsidian'],
        information:["\u00a7a仅用于合成,\u00a7c无法\u00a7a作为下界传送门方块"]
    },
    {
        id:['minecraft:bone_meal'],
        information:["\u00a7c把\u00a7a沙子/魔源粉\u00a7c丢入水中有概率获得"]
    },
    {
        id:['cwe:fake_fluid_tank'],
        information:["\u00a7c这是一个用来展示合成配方gui的机器，具体方法请对着该物品长按w查看"]
    },
    {
        id:['ae2:mysterious_cube'],
        information:['\u00a7a放在地上挖掉它会掉落四种压印模板']
    },
    {
        id:['cwe:fake_mana_pool'],
        information:["\u00a7c这是一个用来展示合成配方gui的机器，具体方法请对着该物品长按w查看"]
    },
    {
        id:['sophisticatedbackpacks:backpack'],
        information:["\u00a7c注意!在升级背包时，背包内物品会被清空"]
    },
    {
        id:[/sophisticatedbackpacks:.*_backpack/],
        information:["\u00a7c注意!在升级背包时，背包内物品会被清空"]
    },
    {
        id:['kubejs:swift_alloy_key'],
        information:['\u00a7a或许可以拿来右键某个钥匙孔']
    },
    {
        id:['ars_nouveau:enchanting_apparatus'],
        information:['\u00a7a使用蓝图大炮将我预先准备好的结构打印到世界中,\u00a7c然后拿着迅金锭右键迅金块即可']
    }]

REIEvents.information(event => {
    tooltips_rei_information.forEach(informations => {
        event.addItem(informations.id,'信息',[informations.information])
    })
})

ItemEvents.tooltip(tooltip =>{
    tooltips_rei_information.forEach(item_tooltip =>{
        tooltip.add(item_tooltip.id,item_tooltip.information)
    })
})