ServerEvents.recipes(event =>{
    const id_prefix = "compact_world:recipes/industrialforegoing/laser_drill_ore/"

    /**
    {
     catalyst:,
     output:,
     rarity:[{
        "blacklist":{},
        "depth_max":255,
        "depth_min":0,
        "weight":1,
        "whitelist":{}
     }],
     id:''
    }
    */
    const reicpes = [
    {
        catalyst:'industrialforegoing:laser_lens12',
        output:'minecraft:raw_iron',
        rarity:[{
            "blacklist":{},
            "depth_max":255,
            "depth_min":0,
            "weight":1,
            "whitelist":{}
        }],
        id:'raw_iron'
    },
    {
        catalyst:'kubejs:lens_of_blazing',
        output:'minecraft:ancient_debris',
        rarity:[{
           "blacklist":{},
           "depth_max":255,
           "depth_min":0,
           "weight":40,
           "whitelist":{}
        }],
        id:'lens_of_blazing_ancient_debris'
    },
    {
        catalyst:'kubejs:lens_of_blazing',
        output:'minecraft:netherite_scrap',
        rarity:[{
           "blacklist":{},
           "depth_max":255,
           "depth_min":0,
           "weight":50,
           "whitelist":{}
        }],
        id:'lens_of_blazing_netherite_scrap'
    },
    {
        catalyst:'kubejs:lens_of_blazing',
        output:'minecraft:netherite_ingot',
        rarity:[{
           "blacklist":{},
           "depth_max":255,
           "depth_min":0,
           "weight":5,
           "whitelist":{}
        }],
        id:'lens_of_blazing_netherite_ingot'
    },
    {
        catalyst:'kubejs:lens_of_blazing',
        output:'spirit:soul_steel_ingot',
        rarity:[{
           "blacklist":{},
           "depth_max":255,
           "depth_min":0,
           "weight":8,
           "whitelist":{}
        }],
        id:'lens_of_blazing_spirit_soul'
    },
    {
        catalyst:'kubejs:lens_of_blazing',
        output:'minecraft:gold_ingot',
        rarity:[{
           "blacklist":{},
           "depth_max":255,
           "depth_min":0,
           "weight":20,
           "whitelist":{}
        }],
        id:'lens_of_blazing_gold_ingot'
    },
    {
        catalyst:'kubejs:lens_of_blazing',
        output:'minecraft:iron_ingot',
        rarity:[{
           "blacklist":{},
           "depth_max":255,
           "depth_min":0,
           "weight":20,
           "whitelist":{}
        }],
        id:'lens_of_blazing_iron_ingot'
    }]

    reicpes.forEach(recipe =>{
        event.recipes.industrialforegoing.laser_drill_ore(recipe.output,recipe.catalyst,recipe.rarity).id(`${id_prefix}${recipe.id}`)
    })
})