ServerEvents.recipes(event =>{
    const id_prefix = 'compact_world:recipes/elementalcraft/infusion/'
    /**
    {
     element_amount:,
     element_type:,
     input:,
     output:,
     id:`${id_prefix}`
    }
    */
    const recipes = [
        {
            element_amount:200,
            element_type:'fire',
            input:items('minecraft:polished_andesite'),
            output:items('minecraft:basalt'),
            id:`${id_prefix}basalt`
        },
        {
            element_amount:200,
            element_type:'fire',
            input:items('elementalcraft:whiterock'),
            output:items('elementalcraft:whiterock_burnt'),
            id:`${id_prefix}whiterock_burnt`
        },
        {
            element_amount:500,
            element_type:'water',
            input:items('minecraft:polished_andesite'),
            output:items('ars_nouveau:sourcestone'),
            id:`${id_prefix}sourcestone`
        },
        {
            element_amount:200,
            element_type:'fire',
            input:items('kubejs:blank_element_ball'),
            output:items('kubejs:trace_fire_element_ball'),
            id:`${id_prefix}trace_fire_element_ball`
        },
        {
            element_amount:200,
            element_type:'air',
            input:items('minecraft:sand'),
            output:items('minecraft:soul_sand'),
            id:`${id_prefix}soul_sand`
        },
        {
            element_amount:500,
            element_type:'earth',
            input:items('ars_nouveau:archwood_planks'),
            output:items('kubejs:gem_earth'),
            id:`${id_prefix}gem_earth`
        },
        {
            element_amount:200,
            element_type:"water",
            input:items('naturesaura:bottle_two_the_rebottling'),
            output:items('kubejs:bottle_water'),
            id:`${id_prefix}bottle_water`
        },
        {
            element_amount:100,
            element_type:"earth",
            input:items('elementalcraft:inert_crystal'),
            output:items('elementalcraft:earthcrystal'),
            id:`${id_prefix}earthcrystal`
        },
        {
            element_amount:1000,
            element_type:'water',
            input:items('ars_nouveau:blue_archwood_log'),
            output:items('kubejs:gem_water'),
            id:`${id_prefix}gem_water`
        },
        {
            element_amount:500,
            element_type:'fire',
            input:items('kubejs:gem_water'),
            output:items('ae2:silicon'),
            id:`${id_prefix}silicon`
        }]

    recipes.forEach(recipe =>{
        event.custom({
            "type": "elementalcraft:infusion",
            "element_amount":recipe.element_amount,
            "element_type":recipe.element_type,
            "input":recipe.input,
            "output":recipe.output
        }).id(recipe.id)
    })
})