ServerEvents.recipes(event =>{
    const id_prefix = 'compact_world:recipes/minecraft/smithing/'
    /**
    {
     output:,
     base_input:,
     addition_input:,
     id:`${id_prefix}`
    }
    */
    const recipes = [
        {
            output:'functionalstorage:gold_upgrade',
            base_input:'kubejs:functionalstorage_upgrade_base',
            addition_input:'minecraft:gold_block',
            id:`${id_prefix}functionalstorage_gold_upgrade`
        },
        {
            output:'sophisticatedstorage:basic_to_gold_tier_upgrade',
            base_input:'sophisticatedstorage:upgrade_base',
            addition_input:'minecraft:gold_block',
            id:`${id_prefix}sophisticatedstorage_basic_to_gold_tier_upgrade`
        },
        {
            output:'sophisticatedbackpacks:stack_upgrade_tier_2',
            base_input:'sophisticatedbackpacks:upgrade_base',
            addition_input:'minecraft:gold_block',
            id:`${id_prefix}sophisticatedbackpacks_stack_upgrade_tier_2`
        },
        {
            output:'create:mechanical_saw',
            base_input:'create:andesite_casing',
            addition_input:'elementalcraft:drenched_saw_blade',
            id:`${id_prefix}mechanical_saw`
        },
        {
            output:'sophisticatedstorage:basic_to_diamond_tier_upgrade',
            base_input:'sophisticatedstorage:basic_to_gold_tier_upgrade',
            addition_input:'minecraft:diamond',
            id:`${id_prefix}basic_to_diamond_tier_upgrade`
        },
        {
            output:'sophisticatedstorage:gold_to_diamond_tier_upgrade',
            base_input:'minecraft:gold_ingot',
            addition_input:'minecraft:diamond',
            id:`${id_prefix}gold_to_diamond_tier_upgrade`
        },
        {
            output:'functionalstorage:diamond_upgrade',
            base_input:'functionalstorage:gold_upgrade',
            addition_input:'minecraft:diamond',
            id:`${id_prefix}diamond_upgrade`
        },
        {
            output:'ae2things:disk_housing',
            base_input:'ae2:item_cell_housing',
            addition_input:'sophisticatedstorage:basic_to_diamond_tier_upgrade',
            id:`${id_prefix}disk_housing`
        },
        {
            output:'expatternprovider:wireless_connect',
            base_input:'entangled:block',
            addition_input:'ae2:fluix_glass_cable',
            id:`${id_prefix}wireless_connect`
        },
        {
            output:'expatternprovider:wireless_tool',
            base_input:'entangled:item',
            addition_input:'ae2:fluix_glass_cable',
            id:`${id_prefix}wireless_tool`
        },
        {
            output:'xnet:connector_yellow',
            base_input:'laserio:laser_node',
            addition_input:'4x minecraft:yellow_dye',
            id:`${id_prefix}connector_yellow`
        },
        {
            output:'thermal:upgrade_augment_1',
            base_input:'botania:rune_water',
            addition_input:'botania:terrasteel_ingot',
            id:`${id_prefix}upgrade_augment_1`
        },
        {
            output:'thermal:upgrade_augment_2',
            base_input:'thermal:upgrade_augment_1',
            addition_input:'thermal:apatite_block',
            id:`${id_prefix}upgrade_augement_2`
        },
        {
            output:'thermal:upgrade_augment_3',
            base_input:'thermal:upgrade_augment_2',
            addition_input:'mekanism:alloy_infused',
            id:`${id_prefix}upgrade_augment_3`
        },
        {
            output:'mekanism:alloy_reinforced',
            base_input:'mekanism:alloy_infused',
            addition_input:'powah:crystal_niotic',
            id:`${id_prefix}alloy_reinforced`
        },
        {
            output:'create_new_age:netherite_magnet',
            base_input:'create_new_age:fluxuated_magnetite',
            addition_input:'minecraft:ancient_debris',
            id:`${id_prefix}netherite_magnet`
        },
        {
            output:'mekanism:advanced_tier_installer',
            base_input:'mekanism:basic_tier_installer',
            addition_input:'mekanism:alloy_infused',
            id:`${id_prefix}advanced_tier_installer`
        },
        {
            output:'mekanism:elite_tier_installer',
            base_input:'mekanism:advanced_tier_installer',
            addition_input:'mekanism:elite_control_circuit',
            id:`${id_prefix}elite_tier_installer`
        },
        {
            output:'ironfurnaces:augment_factory',
            base_input:'ironfurnaces:augment_speed',
            addition_input:'mekanism:advanced_tier_installer',
            id:`${id_prefix}augment_factory`
        },
        {
            output:'industrialforegoing:bioreactor',
            base_input:'industrialforegoing:machine_frame_advanced',
            addition_input:'create_new_age:heater',
            id:`${id_prefix}bioreactor`
        },
        {
            output:'powah:energizing_rod_nitro',
            base_input:'powah:energizing_rod_niotic',
            addition_input:'powah:capacitor_nitro',
            id:`${id_prefix}energizing_rod_nitro`
        },
        {
            output:'thermalendergy:endergy_upgrade_2',
            base_input:'thermalendergy:endergy_upgrade_1',
            addition_input:'thermal:enderium_block',
            id:`${id_prefix}thermalendergy_endergy_upgrade_2`
        }]

    recipes.forEach(recipe =>{
        event.recipes.minecraft.smithing(recipe.output,recipe.base_input,recipe.addition_input).id(recipe.id)
    })
})