ServerEvents.recipes(event =>{
    const id_prefix = 'compact_world:recipes/minecraft/stonecutter/'
    /**
    {
     input:,
     output:,
     id:`${id_prefix}`
    }
    */
    const recipes = [
        {
            input:'kubejs:functionalstorage_upgrade_base',
            output:'functionalstorage:pusher_upgrade',
            id:`${id_prefix}pusher_upgrade`
        },
        {
            input:'kubejs:functionalstorage_upgrade_base',
            output:'functionalstorage:puller_upgrade',
            id:`${id_prefix}puller_upgrade`
        },
        {
            input:'kubejs:functionalstorage_upgrade_base',
            output:'functionalstorage:collector_upgrade',
            id:`${id_prefix}collector_upgrade`
        },
        {
            input:'kubejs:spark_upgrade_base',
            output:'botania:spark_upgrade_dispersive',
            id:`${id_prefix}spark_upgrade_dispersive`
        },
        {
            input:'kubejs:spark_upgrade_base',
            output:'botania:spark_upgrade_dominant',
            id:`${id_prefix}spark_upgrade_dominant`
        },
        {
            input:'kubejs:spark_upgrade_base',
            output:'botania:spark_upgrade_recessive',
            id:`${id_prefix}spark_upgrade_recessive`
        },
        {
            input:'kubejs:spark_upgrade_base',
            output:'botania:spark_upgrade_isolated',
            id:`${id_prefix}spark_upgrade_isolated`
        },
        {
            input:'modularrouters:blank_upgrade',
            output:'modularrouters:security_upgrade',
            id:`${id_prefix}security_upgrade`
        },
        {
            input:'modularrouters:blank_upgrade',
            output:'modularrouters:camouflage_upgrade',
            id:`${id_prefix}camouflage_upgrade`
        },
        {
            input:'ars_nouveau:relay',
            output:'ars_nouveau:relay_collector',
            id:`${id_prefix}relay_collector`
        },
        {
            input:'ars_nouveau:relay',
            output:'ars_nouveau:relay_deposit',
            id:`${id_prefix}relay_deposit`
        },
        {
            input:'ars_nouveau:relay',
            output:'ars_nouveau:relay_warp',
            id:`${id_prefix}relay_warp`
        },
        {
            input:'ars_nouveau:relay',
            output:'ars_nouveau:relay_splitter',
            id:`${id_prefix}relay_splitter`
        },
        {
            input:'ars_nouveau:basic_spell_turret',
            output:'ars_nouveau:rotating_spell_turret',
            id:`${id_prefix}rotating_spell_turret`
        },
        {
            input:'ars_nouveau:basic_spell_turret',
            output:'ars_nouveau:spell_turret',
            id:`${id_prefix}spell_turret`
        },
        {
            input:'ars_nouveau:basic_spell_turret',
            output:'ars_nouveau:timer_spell_turret',
            id:`${id_prefix}timer_spell_turret`
        },
        {
            input:'ars_nouveau:relay_splitter',
            output:'ars_nouveau:relay',
            id:`${id_prefix}restore/relay_splitter`
        },
        {
            input:'ars_nouveau:relay_warp',
            output:'ars_nouveau:relay',
            id:`${id_prefix}restore/relay_warp`
        },
        {
            input:'ars_nouveau:relay_deposit',
            output:'ars_nouveau:relay',
            id:`${id_prefix}restore/relay_deposit`
        },
        {
            input:'ars_nouveau:relay_collector',
            output:'ars_nouveau:relay',
            id:`${id_prefix}restore/relay_collector`
        },
        {
            input:'functionalstorage:collector_upgrade',
            output:'kubejs:functionalstorage_upgrade_base',
            id:`${id_prefix}restore/collector_upgrade`
        },
        {
            input:'functionalstorage:puller_upgrade',
            output:'kubejs:functionalstorage_upgrade_base',
            id:`${id_prefix}restore/puller_upgrade`
        },
        {
            input:'functionalstorage:pusher_upgrade',
            output:'kubejs:functionalstorage_upgrade_base',
            id:`${id_prefix}restore/pusher_upgrade`
        }]

    recipes.forEach(recipe =>{
        event.recipes.minecraft.stonecutting(recipe.output,recipe.input).id(recipe.id)
    })
})