ServerEvents.recipes(event =>{
    const id_prefix = 'compact_world:recipes/custom_machinery/source_craftingtable/'

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',20)
    .requireSourcePerTick(50)
    .requireItem('create:shaft',"slot2")
    .requireItem('create:andesite_casing',"slot5")
    .requireItem('elementalcraft:swift_alloy_block',"slot8")
    .produceItem('create:mechanical_press',"slot10")
    .id(`${id_prefix}mechanical_press`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',20)
    .requireSourcePerTick(50)
    .requireItem('spirit:soul_powder',"slot2")
    .requireItem('create:andesite_casing',"slot5")
    .requireItem('kubejs:swift_alloy_hand',"slot8")
    .produceItem('create:deployer',"slot10")
    .id(`${id_prefix}deployer`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',20)
    .requireSourcePerTick(500)
    .requireItem('ars_nouveau:source_jar',"slot2")
    .requireItem('ars_nouveau:arcane_pedestal',"slot5")
    .requireItem('elementalcraft:swift_alloy_block',"slot8")
    .produceItem('ars_nouveau:ritual_brazier',"slot10")
    .id(`${id_prefix}ritual_brazier`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',20)
    .requireSourcePerTick(50)
    .requireItem('create:andesite_alloy',"slot5")
    .requireItem('create:andesite_casing',"slot8")
    .produceItem('create:depot',"slot10")
    .id(`${id_prefix}depot`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',10)
    .requireSourcePerTick(50)
    .requireItem('create:framed_glass',"slot1")
    .requireItem('create:framed_glass',"slot3")
    .requireItem('create:framed_glass',"slot4")
    .requireItem('create:framed_glass',"slot6")
    .requireItem('create:framed_glass',"slot7")
    .requireItem('create:framed_glass',"slot9")
    .requireItem('kubejs:polished_gold_block',"slot2")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot5")
    .requireItem('ars_nouveau:archwood_planks',"slot8")
    .produceItem('ars_nouveau:source_jar',"slot10")
    .id(`${id_prefix}source_jar`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',10)
    .requireSourcePerTick(50)
    .requireItem('ars_nouveau:sourcestone',"slot1")
    .requireItem('ars_nouveau:sourcestone',"slot2")
    .requireItem('ars_nouveau:sourcestone',"slot3")
    .requireItem('ars_nouveau:sourcestone',"slot7")
    .requireItem('ars_nouveau:sourcestone',"slot8")
    .requireItem('ars_nouveau:sourcestone',"slot9")
    .requireItem('kubejs:polished_gold_block',"slot4")
    .requireItem('kubejs:polished_gold_block',"slot6")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot5")
    .produceItem('ars_nouveau:arcane_core',"slot10")
    .id(`${id_prefix}arcane_core`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',10)
    .requireSourcePerTick(50)
    .requireItem('kubejs:polished_gold_block',"slot1")
    .requireItem('kubejs:polished_gold_block',"slot3")
    .requireItem('kubejs:polished_gold_block',"slot4")
    .requireItem('kubejs:polished_gold_block',"slot6")
    .requireItem('kubejs:polished_gold_block',"slot7")
    .requireItem('kubejs:polished_gold_block',"slot9")
    .requireItem('ars_nouveau:sourcestone',"slot2")
    .requireItem('ars_nouveau:sourcestone',"slot8")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot5")
    .produceItem('ars_nouveau:enchanting_apparatus',"slot10")
    .id(`${id_prefix}enchanting_apparatus`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',10)
    .requireSourcePerTick(50)
    .requireItem('ars_nouveau:blank_glyph',"slot5")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot1")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot2")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot3")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot4")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot6")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot7")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot8")
    .requireItem('elementalcraft:swift_alloy_ingot',"slot9")
    .produceItem('ars_nouveau:glyph_sensitive',"slot10")
    .id(`${id_prefix}glyph_sensitive`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',10)
    .requireSourcePerTick(50)
    .requireItem('ars_nouveau:blank_glyph',"slot5")
    .requireItem('elementalcraft:earthcrystal',"slot1")
    .requireItem('elementalcraft:earthcrystal',"slot2")
    .requireItem('elementalcraft:earthcrystal',"slot3")
    .requireItem('elementalcraft:earthcrystal',"slot4")
    .requireItem('elementalcraft:earthcrystal',"slot6")
    .requireItem('elementalcraft:earthcrystal',"slot7")
    .requireItem('elementalcraft:earthcrystal',"slot8")
    .requireItem('elementalcraft:earthcrystal',"slot9")
    .produceItem('ars_nouveau:glyph_crush',"slot10")
    .id(`${id_prefix}glyph_crush`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',10)
    .requireSourcePerTick(100)
    .requireItem(Item.of('naturesaura:aura_bottle',1,'{stored_type:"naturesaura:overworld"}'),"slot2")
    .requireItem(Item.of('naturesaura:aura_bottle',1,'{stored_type:"naturesaura:overworld"}'),"slot4")
    .requireItem(Item.of('naturesaura:aura_bottle',1,'{stored_type:"naturesaura:overworld"}'),"slot6")
    .requireItem(Item.of('naturesaura:aura_bottle',1,'{stored_type:"naturesaura:overworld"}'),"slot8")
    .requireItem('kubejs:mana_powder',"slot5")
    .produceItem(Item.of('naturesaura:token_joy',4),"slot10")
    .id(`${id_prefix}token_joy`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',10)
    .requireSourcePerTick(50)
    .requireItem('botania:fabulous_pool',"slot5")
    .requireItem('botania:bifrost_perm',"slot1")
    .requireItem('botania:bifrost_perm',"slot2")
    .requireItem('botania:bifrost_perm',"slot3")
    .requireItem('botania:bifrost_perm',"slot4")
    .requireItem('botania:bifrost_perm',"slot6")
    .requireItem('botania:bifrost_perm',"slot7")
    .requireItem('botania:bifrost_perm',"slot8")
    .requireItem('botania:bifrost_perm',"slot9")
    .produceItem('cwe:mana_booster',"slot10")
    .id(`${id_prefix}mana_booster`)

    event.recipes.custommachinery.custom_machine('cwe:source_craftingtable',200)
    .requireSource(50000)
    .requireItem('kubejs:sky_nugget',"slot4")
    .requireItem('kubejs:sky_nugget',"slot5")
    .requireItem('kubejs:sky_nugget',"slot6")
    .requireItem('botania:livingwood_log',"slot1")
    .requireItem('botania:livingwood_log',"slot2")
    .requireItem('botania:livingwood_log',"slot3")
    .requireItem('botania:livingwood_log',"slot7")
    .requireItem('botania:livingwood_log',"slot8")
    .requireItem('botania:livingwood_log',"slot9")
    .produceItem('mythicbotany:yggdrasil_branch',"slot10")
    .id(`${id_prefix}yggdrasil_branch`)
})