ServerEvents.recipes(event =>{
    const id_prefix = 'compact_world:recipes/botania/mana_infusion/'
    /**
    {
     input:,
     output:,
     under_block:,
     mana:,
     id:`${id_prefix}`
    }
    */
    const recipes = [
        {
            input:'minecraft:gold_ingot',
            output:'botania:manasteel_ingot',
            under_block:false,
            mana:100,
            id:`${id_prefix}manasteel_ingot`
        },
        {
            input:'minecraft:gold_block',
            output:'botania:manasteel_block',
            under_block:false,
            mana:1000,
            id:`${id_prefix}manasteel_block`
        },
        {
            input:'kubejs:shining_gold_mix',
            output:'minecraft:gold_ingot',
            under_block:false,
            mana:100,
            id:`${id_prefix}gold_ingot`
        },
        {
            input:'thermal:gold_dust',
            output:'kubejs:mana_powder',
            under_block:false,
            mana:10,
            id:`${id_prefix}kjs_mana_powder`
        },
        {
            input:'create:framed_glass',
            output:'botania:mana_glass',
            under_block:false,
            mana:10,
            id:`${id_prefix}mana_glass`
        },
        {
            input:'naturesaura:sky_ingot',
            output:'4x kubejs:spark_upgrade_base',
            under_block:false,
            mana:100,
            id:`${id_prefix}spark_upgrade_base`
        },
        {
            input:'ae2:quartz_block',
            output:'ae2:flawless_budding_quartz',
            under_block:false,
            mana:1000,
            id:`${id_prefix}flawless_budding_quartz`
        },
        {
            input:'ae2:certus_quartz_dust',
            output:'ae2:certus_quartz_crystal',
            under_block:false,
            mana:10,
            id:`${id_prefix}certus_quartz_crystal`
        },
        {
            input:'ae2:fluix_dust',
            output:'ae2:fluix_crystal',
            under_block:false,
            mana:10,
            id:`${id_prefix}fluix_crystal`
        },
        {
            input:'kubejs:gem_earth',
            output:'botania:grass_seeds',
            under_block:false,
            mana:1000,
            id:`${id_prefix}grass_seeds`
        },
        {
            input:'spirit:soul_powder',
            output:'botania:mana_powder',
            under_block:false,
            mana:10,
            id:`${id_prefix}botania_mana_powder`
        },
        {
            input:'minecraft:flint',
            output:'minecraft:gunpowder',
            under_block:'spirit:soul_steel_block',
            mana:100,
            id:`${id_prefix}gunpowder`
        },
        {
            input:'minecraft:polished_andesite',
            output:'kubejs:obsidian',
            under_block:'spirit:soul_steel_block',
            mana:100,
            id:`${id_prefix}obsidian`
        },
        {
            input:'modularrouters:speed_upgrade',
            output:'modularrouters:stack_upgrade',
            under_block:'spirit:soul_steel_block',
            mana:500,
            id:`${id_prefix}stack_upgrade`
        },
        {
            input:'minecraft:polished_andesite',
            output:'minecraft:netherrack',
            under_block:'minecraft:magma_block',
            mana:100,
            id:`${id_prefix}netherrack`
        },
        {
            input:'minecraft:lava_bucket',
            output:'minecraft:magma_block',
            under_block:'spirit:soul_steel_block',
            mana:500,
            id:`${id_prefix}magma_block`
        },
        {
            input:'naturesaura:token_joy',
            output:'naturesaura:token_euphoria',
            under_block:'kubejs:soul_steel_casing',
            mana:500,
            id:`${id_prefix}token_euphoria`
        },
        {
            input:'ae2:certus_quartz_crystal',
            output:'kubejs:mana_certus_quartz_crystal',
            under_block:'kubejs:token_euphoria_catalyst',
            mana:1000,
            id:`${id_prefix}mana_certus_quartz_crystal`
        },
        {
            input:'malum:eldritch_spirit',
            output:'malum:aqueous_spirit',
            under_block:'create:brass_casing',
            mana:10000,
            id:`${id_prefix}aqueous_spirit`
        }]

    recipes.forEach(recipe =>{
        if( recipe.under_block == false){
            event.recipes.botania.mana_infusion(recipe.output,recipe.input,recipe.mana).id(recipe.id)
        }else{
            event.recipes.botania.mana_infusion(recipe.output,recipe.input,recipe.mana,recipe.under_block).id(recipe.id)
        }
    })
})